// Aspect Ratios for UI
export const ASPECT_RATIOS = ['2:1', '16:9', '3:2', '1:1', '2:3', '9:16', '1:2'] as const;

// Aspect Ratios supported directly by the Imagen API
export const API_SUPPORTED_ASPECT_RATIOS = ["16:9" , "3:2" , "1:1" , "2:3" , "9:16" ];

// --- VEO Constants ---
export const VEO_ASPECT_RATIOS: ReadonlyArray<"16:9" | "1:1" | "9:16"> = ['16:9', '1:1', '9:16'] as const;

export const VEO_MEME_PROMPTS = [
    { label: '一切都很好', prompt: "『This is Fine』迷因裡的柴犬，戴著太陽眼鏡坐在燃燒的沙灘椅上，周圍是海嘯警報，牠啜飲著一杯小雨傘著火的飲料，輕聲說：『沒事的。』" },
    { label: '永恆的節拍', prompt: "薛西弗斯（Sisyphus）在一個地下電音派對上擔任 DJ，音樂是他推著巨石上山的沉重撞擊聲，每當巨石滾落時就是一次『Drop』，台下是面無表情、隨節奏搖擺的殭屍。" },
    { label: '企業塗鴉', prompt: "一位面帶虛偽微笑的人力資源經理，在午夜用過期咖啡和螢光筆，在公司大樓外牆上噴塗『我們是個大家庭』和『提升協同效應』等標語。" },
    { label: '深海瘟疫', prompt: "一位中世紀瘟疫醫生穿著全套鳥嘴面具裝備，在充滿塑膠袋和廢棄物的混濁海底「治療」一隻變異的魚。" },
    { label: '克蘇魯吃播', prompt: "一位美食網紅正直播開箱一本用海草包裹、會蠕動的《死靈之書》，並用叉子戳著書頁上長出的觸手，對著鏡頭說：『嘿，各位粉絲，今天我們來嚐嚐遠古的恐懼！』" },
    { label: '究極鍛鍊', prompt: "『Gigachad』迷因裡的那個男人，在健身房裡不是舉啞鈴，而是用槓鈴舉著自己巨大的下巴，鏡子裡反射出他完美的下顎線。" },
    { label: '末日騎士', prompt: "『分心男友』迷因裡的那個男友，騎著一輛重型機車，回頭看著一個新出現的「災難預兆」（彗星），而他的女友（代表「現有的全球危機」）在他身後憤怒地大喊。" },
    { label: '太空垃圾人', prompt: "一位在太空站工作的清潔工，穿著笨重的太空服，用一支長長的夾子費力地將一個漂浮的披薩盒塞進已經滿出來的太空垃圾桶裡。" },
    { label: '賽博禪修', prompt: "一個有著七彩跑馬燈的電競主機，被放置在日本寺廟的枯山水庭園中央，發出嗡嗡的風扇聲，試圖在數位世界與現實之間尋求內心的平靜。" },
    { label: '地獄廚房', prompt: "一位惡魔在電視廚藝大賽上，用靈魂和悔恨作為調味料，烹煮一道名叫「永恆的折磨」的菜餚，評審嚐了一口後流下了感動（或痛苦）的淚水。" },
    { label: '存在主義偵探', prompt: "一個被畫壞的火柴人偵探，站在一片虛無的白色背景中，對著地上一條鉛筆線索喃喃自語：『這一切的意義是什麼？是誰畫下了我？』" },
    { label: 'NFT農夫', prompt: "一位穿著格子衫的農夫，在他-的虛擬農場裡，驕傲地抱著一顆他剛「挖礦」挖出來、價值三百萬美金的巨大像素化南瓜 JPEG 檔案。" },
    { label: '線上對線', prompt: "一位鍵盤戰士戴著VR頭盔，坐在堆滿能量飲料空罐的電競椅上，正用一套價值不菲的模擬器，與論壇上的另一個網友進行激烈的「真人快打」。" },
    { label: '演算法管理員', prompt: "YouTube 的演算法化身為一個疲憊的圖書館員，面對堆積如山的影片，它隨手拿起一個貓咪影片和一個陰謀論影片，然後把它們一起蓋上「推薦」的印章。" },
    { label: '打卡聖地', prompt: "一位喪屍網紅背著登山包，在傾頹的末日城市廢墟中擺出陽光開朗的姿勢自拍，並在照片下標註：#末日旅行 #廢土風 #活在當下。" },
    { label: '選擇困難症', prompt: "哲學家沙特推著購物車，在宜家（IKEA）面對兩款幾乎一模一樣的置物櫃，陷入了關於「自由選擇的重負」的深度思考，最終癱坐在地上。" },
    { label: '情緒勞動', prompt: "一位微笑面具人（Wojak 迷因）在咖啡店擔任咖啡師，面具上掛著燦爛的笑容，但面具下滴著眼淚，為客人拉花時手微微顫抖。" },
    { label: '精神內耗', prompt: "兩隻正在打架的貓（Cat Fight 迷因），在山頂上試圖一起完成一個雙人瑜珈動作，結果扭打了起來。" },
    { label: '濾鏡人生', prompt: "一位開了十級美顏濾鏡的網路主播，在羅馬競技場前直播，濾鏡嚴重變形，把後面的古蹟都P成了光滑的圓柱體。" },
    { label: '安慰劑市場', prompt: "一位穿著白袍的庸醫，在農夫市集上販售他自己裝瓶的「正能量空氣」和「有機安慰劑藥丸」，生意絡繹不絕。" },
    { label: '知識的詛咒', prompt: "一位剛學會上網的穴居人，在大學講堂裡用石板展示他從網路論壇上學到的「地球是平的」理論，台下學生一片茫然。" },
    { label: '待辦事項', prompt: "死神在他的車庫裡，拿著一把巨大的鐮刀，笨拙地修理一台卡住的印表機，因為「死亡名單」列印不出來，導致他今天的工作嚴重延遲。" },
    { label: '觀景窗悖論', prompt: "薛丁格的貓身穿迷彩服，拿著一台相機，悄悄地拍攝一隻既存在又不存在的獅子。" },
    { label: '資本主義的抉擇', prompt: "一個身穿西裝的華爾街之狼，在超市的冰淇淋區，正在用複雜的股票分析模型，計算哪一種口味的冰淇淋能帶來最高的「幸福感投資報酬率」。" },
    { label: '無盡的循環', prompt: "一隻正在電腦前打字的倉鼠，在地下酒吧擔任鼓手，用牠小小的爪子在一個滾輪改造的鼓上瘋狂奔跑，製造出快速但單調的節奏。" },
    { label: '畫大餅', prompt: "一位新創公司的 CEO，穿著黑色高領毛衣，在空無一物的會議室裡，對著一群想像出來的投資人，激情地介紹他那個能「顛覆人類生活」的共用單車App。" },
    { label: '數位典藏', prompt: "一個病毒（電腦病毒），在博物館裡欣賞著一幅由藍白當機畫面構成的數位藝術品，看得入了迷。" },
    { label: '物理Bug', prompt: "一位遊戲裡的 NPC（非玩家角色），因為程式碼出錯，從飛機上跳下來後卡在了半空中，保持著自由落體的姿勢，表情茫然。" },
    { label: '最後一哩路', prompt: "一位外送平台的外送員，騎著一匹筋疲力盡的殭屍馬，背著外送箱，穿梭在充滿惡靈的街道上，只是為了一單即將超時的訂單。" },
    { label: '資訊繭房', prompt: "一個被演算法餵養大的年輕人，穿著睡衣癱在沙發上，電視、手機、平板同時播放著同一個網紅推薦的同一部劇，爆米花是演算法推薦的口味。" }
];

export const UNIFIED_DIRECTOR_STYLES = [
    { name: '世界知名導演', prompt: '' },
    { name: 'Abbas Kiarostami (阿巴斯·奇亞羅斯塔米)', prompt: '伊朗新浪潮，模糊紀錄片與劇情片的界線，兒童視角，對生命意義的哲學探討，如《橄欖樹下的情人》。' },
    { name: 'Akira Kurosawa (黑澤明)', prompt: '武士精神與榮譽，大氣磅礴的史詩感，運用多機位拍攝和精準的構圖，如《七武士》般古典而永恆。' },
    { name: 'Alfonso Cuarón (阿方索·卡隆)', prompt: '長鏡頭的敘事魔力，如《人類之子》般緊張壓抑的科幻末日，或《羅馬》般細膩的個人史詩，情感豐富。' },
    { name: 'Andrei Tarkovsky (安德烈·塔可夫斯基)', prompt: '詩意的長鏡頭，對記憶、信仰和自然的深刻思考，緩慢而沉靜的節奏，如《潛行者》。' },
    { name: 'Ang Lee (李安)', prompt: '細膩的情感刻畫，東西方文化交融的衝突與和解，如《臥虎藏龍》般詩意與武俠的結合，或《少年Pi的奇幻漂流》般壯麗的視覺史詩。' },
    { name: 'Antoine Fuqua', prompt: 'The scene is directed in the signature style of Antoine Fuqua. The action is visceral and hard-hitting, with a focus on character-driven conflict and the brutal consequences of violence. The visuals are often dark, stylish, and intense.' },
    { name: 'Ava DuVernay (艾娃·杜威內)', prompt: '歷史題材中的種族與正義，強大的情感驅動，如《逐夢大道》般鼓舞人心。' },
    { name: 'Bernardo Bertolucci (貝爾納多·貝托魯奇)', prompt: '史詩般的政治與情慾糾葛，華麗的視覺風格，如《末代皇帝》。' },
    { name: 'Bong Joon-ho (奉俊昊)', prompt: '社會批判與黑色幽默，類型片結構下的階級矛盾，如《寄生上流》般從荒誕走向驚悚的氛圍。' },
    { name: 'Brad Bird', prompt: 'The scene is directed in the signature style of Brad Bird. The action is inventive, beautifully choreographed, and spatially clear, whether in animation or live-action. The sequences are a masterclass in building suspense and excitement through clever staging.' },
    { name: 'Chad Stahelski (John Wick)', prompt: 'The scene is directed in the signature style of Chad Stahelski. Showcase "gun-fu" with clean, wide-angle long takes that emphasize choreography. The lighting is heavily influenced by neon, with deep shadows and a sleek, modern, and brutal aesthetic.' },
    { name: 'Chloé Zhao (趙婷)', prompt: '自然風景中的個人故事，寫實的鏡頭捕捉邊緣人物的生存狀態，如《游牧人生》般詩意而真實。' },
    { name: 'Christopher McQuarrie', prompt: 'The scene is directed in the signature style of Christopher McQuarrie. Feature complex, high-stakes action sequences that are meticulously planned and executed with a focus on practical effects and clear, coherent geography.' },
    { name: 'Christopher Nolan (克里斯多福·諾蘭)', prompt: '燒腦的非線性敘事，時間與記憶的哲學探討，IMAX級的宏大視覺效果，低沉配樂，如《全面啟動》或《星際效應》。' },
    { name: 'Clint Eastwood (克林·伊斯威特)', prompt: '經典的西部片或犯罪片風格，深沉的男性氣概，簡單而有力的敘事，如《不可饒恕》。' },
    { name: 'Coen Brothers (科恩兄弟)', prompt: '黑色幽默與荒誕諷刺，犯罪故事與意外事件，獨特的對白和地域特色，如《冰血暴》。' },
    { name: 'Corey Yuen (元奎)', prompt: 'The scene is directed in the signature style of Corey Yuen. The action is a showcase of high-flying, acrobatic martial arts. The choreography is elegant and powerful, blending traditional kung fu with modern cinematic techniques for maximum visual impact.' },
    { name: 'Daniels - Kwan & Scheinert (丹尼爾·關 & 丹尼爾·舒奈特)', prompt: '瘋狂的創意和天馬行空的敘事，多重宇宙的視覺盛宴，如《媽的多重宇宙》般充滿想像力。' },
    { name: 'David Ayer', prompt: 'The scene is directed in the signature style of David Ayer. The action is gritty, tactical, and grounded in street-level realism. The camera is often in the thick of the fight, capturing the raw and chaotic nature of urban combat.' },
    { name: 'David Fincher (大衛·芬奇)', prompt: '冷峻的藍灰色調，精準的剪輯和鏡頭控制，探討人性的黑暗面，如《社群網戰》或《火線追緝令》般的懸疑與緊張。' },
    { name: 'David Leitch', prompt: 'The scene is directed in the signature style of David Leitch. A former stuntman, the action is clean, creative, and built around incredible stunt work. The choreography is top-notch, with a neon-lit, stylish, and often humorous tone.' },
    { name: 'David Lynch (大衛·林奇)', prompt: '超現實主義，詭異的夢境與潛意識，扭曲的現實和神秘符號，如《穆赫蘭大道》般迷幻。' },
    { name: 'Denis Villeneuve', prompt: 'The scene is directed in the signature style of Denis Villeneuve. The action is tense, brutal, and grounded in a stark reality. Use a muted color palette and immersive sound design to create a sense of overwhelming scale and suspense.' },
    { name: 'Doug Liman', prompt: 'The scene is directed in the signature style of Doug Liman. The action has a sense of grounded, innovative realism. The camera work is often handheld and immersive, creating a feeling of immediacy and clever, on-the-fly problem-solving.' },
    { name: 'Edgar Wright', prompt: 'The scene is directed in the signature style of Edgar Wright. The action is tightly choreographed to the rhythm of the music, with kinetic, whip-pan editing, and a heavy use of visual comedy and creative sound design.' },
    { name: 'Edward Yang (楊德昌)', prompt: '台北都市生活群像，理性而冷靜的鏡頭，對人際關係和現代化的批判，如《牯嶺街少年殺人事件》。' },
    { name: 'F. Gary Gray', prompt: 'The scene is directed in the signature style of F. Gary Gray. Craft slick, large-scale action sequences, especially car chases, with a high-energy, commercial aesthetic. The action is exciting, well-shot, and often has a heist or street-racing flavor.' },
    { name: 'Federico Fellini (費德里柯·費里尼)', prompt: '魔幻現實主義，對社會和人性的諷刺，嘉年華般的熱鬧場景與荒誕元素，如《八又二分之一》。' },
    { name: 'François Truffaut (楚浮)', prompt: '新浪潮的浪漫主義，對童年和愛情的探索，流暢的敘事和人道關懷，如《四百擊》。' },
    { name: 'Gareth Evans', prompt: 'The scene is directed in the signature style of Gareth Evans. Showcase brutal and intricate Silat martial arts with dynamic, flowing camera work that moves with the fighters. The editing is fast-paced, highlighting the raw impact of every blow.' },
    { name: 'George Miller (Mad Max)', prompt: 'The scene is directed in the signature style of George Miller. Create a sense of practical, kinetic chaos. Use tight, center-framed shots on the action, rapid-fire editing, and a vibrant, often monochromatic desert color palette to create relentless forward momentum.' },
    { name: 'Greta Gerwig (葛莉塔·潔薇)', prompt: '女性成長與自我探索，充滿智慧和幽默的對白，如《淑女鳥》或《小婦人》般真誠而生動。' },
    { name: 'Guillermo del Toro (吉勒摩·戴托羅)', prompt: '哥德式奇幻美學，怪物與人性的界線模糊，如《水形物語》般黑暗浪漫的童話故事。' },
    { name: 'Guy Ritchie', prompt: 'The scene is directed in the signature style of Guy Ritchie. Use a frenetic mix of speed-ramping, quick cuts, and gritty, street-level action, often accompanied by witty narration or dialogue and a cool, stylish soundtrack.' },
    { name: 'Hayao Miyazaki (宮崎駿)', prompt: '手繪動畫的奇幻世界，環保與和平的主題，充滿想像力的生物和場景，如《神隱少女》般溫暖而深邃。' },
    { name: 'Hirokazu Kore-eda (是枝裕和)', prompt: '平實細膩的家庭故事，日常對話中的情感流動，呈現《小偷家族》般溫暖而感傷的現實主義。' },
    { name: 'Hou Hsiao-Hsien (侯孝賢)', prompt: '台灣新電影代表，長鏡頭的日常捕捉，對歷史與鄉愁的詩意呈現，如《悲情城市》。' },
    { name: 'Ingmar Bergman (英格瑪·柏格曼)', prompt: '對信仰、死亡和人際關係的哲學探討，黑白影像的強烈對比，特寫鏡頭中的人物內心，如《第七封印》。' },
    { name: 'J.J. Abrams', prompt: 'The scene is directed in the signature style of J.J. Abrams. The action is fast-paced and full of spectacle, characterized by signature lens flares, a constantly moving camera, and a sense of mystery and adventure.' },
    { name: 'James Cameron', prompt: 'The scene is directed in the signature style of James Cameron. Combine high-stakes, technologically advanced action with a strong emotional core. Use a cool, blue-tinted color palette, and depict large-scale, meticulously detailed set pieces.' },
    { name: 'James Wan', prompt: 'The scene is directed in the signature style of James Wan. The camera is incredibly dynamic, moving through environments in long, seemingly impossible takes. The action is a blend of horror kinetics and high-octane spectacle.' },
    { name: 'Jean-Luc Godard (尚盧·高達)', prompt: '法國新浪潮的代表，跳躍剪輯，打破第四道牆，對電影形式的實驗，如《斷了氣》。' },
    { name: 'Jia Zhangke (賈樟柯)', prompt: '中國社會變遷下的個體命運，寫實而沉鬱的風格，大量非專業演員，如《三峽好人》。' },
    { name: 'John Cassavetes (約翰·卡薩維蒂)', prompt: '寫實的即興表演，對人物心理的深入挖掘，獨立電影的粗獷感，如《受影響的女人》。' },
    { name: 'John McTiernan', prompt: 'The scene is directed in the signature style of John McTiernan. Craft suspenseful, spatially aware action sequences. Utilize wide-angle lenses and clever blocking to make the environment a key part of the action, with a focus on a lone, resourceful hero.' },
    { name: 'John Woo (吳宇森)', prompt: 'The scene is directed in the signature style of John Woo. Feature hyper-stylized "heroic bloodshed" gun-fu, with dramatic slow-motion, dynamic dove-like visual motifs, and intense, emotionally charged action.' },
    { name: 'Johnnie To (杜琪峰)', prompt: 'The scene is directed in the signature style of Johnnie To. Feature meticulously staged, static-camera shootouts where positioning and strategy are key. The action is tense, minimalist, and punctuated by sudden bursts of violence.' },
    { name: 'Justin Lin', prompt: 'The scene is directed in the signature style of Justin Lin. Known for large-scale, physics-defying vehicular action. The sequences are elaborate, over-the-top, and executed with a slick, blockbuster sensibility.' },
    { name: 'Kathryn Bigelow', prompt: 'The scene is directed in the signature style of Kathryn Bigelow. Employ a gritty, visceral, and immersive documentary style. Use handheld cameras and long takes to create a sense of chaotic realism and intense, life-or-death tension.' },
    { name: 'Kenji Mizoguchi (溝口健二)', prompt: '對女性悲劇命運的深刻描繪，長鏡頭與精緻的構圖，如《雨月物語》般古典而淒美。' },
    { name: 'Kim Jee-woon (金知雲)', prompt: 'The scene is directed in the signature style of Kim Jee-woon. Blend stylish, genre-inflected action with high-octane energy. The visuals are polished and dynamic, whether in a Western-style shootout, a spy thriller chase, or a tale of brutal revenge.' },
    { name: 'Lars von Trier (拉斯·馮·提爾)', prompt: '極具爭議的實驗性風格，對人性的黑暗面進行極端探索，手持攝影與自然光，如《破浪》。' },
    { name: 'Lena Dunham (莉娜·杜漢)', prompt: '年輕女性在城市中的掙扎與成長，帶有自嘲與真實感的幽默，如《女孩我最大》的坦率。' },
    { name: 'Luc Besson', prompt: 'The scene is directed in the signature style of Luc Besson. The action is slick, highly stylized, and has a European "cinéma du look" sensibility. The visuals are colorful and cool, often centered around a memorable, formidable protagonist.' },
    { name: 'Luis Buñuel (路易斯·布紐爾)', prompt: '超現實主義，對宗教和資產階級的諷刺，夢境與現實的交織，如《中產階級的審慎魅力》。' },
    { name: 'Martin Scorsese (馬丁·史柯西斯)', prompt: '粗獷寫實的城市生活，罪惡與救贖的主題，快速剪輯與獨白，呈現《好傢伙》或《計程車司機》般的黑幫史詩。' },
    { name: 'Matthew Vaughn', prompt: 'The scene is directed in the signature style of Matthew Vaughn. Showcase inventive, hyper-violent, and flawlessly choreographed action set pieces, often set to anachronistic music, with a slick, energetic, and unapologetically stylish flair.' },
    { name: 'Michael Bay', prompt: 'The scene is directed in the signature style of Michael Bay. Incorporate "Bayhem" aesthetics: massive explosions, epic-scale destruction, sweeping low-angle tracking shots, dramatic lens flares, and a high-contrast, saturated color palette.' },
    { name: 'Michael Haneke (麥可·哈內克)', prompt: '對現代社會的冷酷批判，心理驚悚與暴力，長鏡頭和疏離感，如《鋼琴教師》。' },
    { name: 'Neill Blomkamp', prompt: 'The scene is directed in the signature style of Neill Blomkamp. Blend gritty, realistic action with futuristic sci-fi concepts. The visuals have a documentary feel, with realistic VFX and a focus on social commentary within the action.' },
    { name: 'Park Chan-wook (朴贊郁)', prompt: 'The scene is directed in the signature style of Park Chan-wook. The action is a brutal, beautifully composed, and often single-take "hallway fight" sequence. The violence is raw and visceral, framed with a meticulous, almost operatic elegance.' },
    { name: 'Paul Greengrass', prompt: 'The scene is directed in the signature style of Paul Greengrass. Utilize a shaky-cam, documentary-like "cinéma vérité" style. The editing is rapid and disorienting, creating a chaotic and intensely realistic sense of immersion in the action.' },
    { name: 'Paul Thomas Anderson (保羅·湯瑪斯·安德森)', prompt: '複雜的人物心理，社會邊緣人的故事，流暢的攝影機運動，如《黑金企業》般史詩。' },
    { name: 'Paul Verhoeven', prompt: 'The scene is directed in the signature style of Paul Verhoeven. The action is shockingly violent, over-the-top, and often serves as a satirical commentary on society. The visuals are graphic, explosive, and unapologetically brutal.' },
    { name: 'Pedro Almodóvar (佩德羅·阿莫多瓦)', prompt: '鮮豔的色彩與巴洛克風格，複雜的女性視角和情感糾葛，西班牙文化與戲劇性，如《玩美女人》。' },
    { name: 'Peter Berg', prompt: 'The scene is directed in the signature style of Peter Berg. The action is chaotic, intense, and grounded in a sense of patriotic, real-world heroism. The editing is fast and the camera is often right in the middle of the conflict.' },
    { name: 'Prachya Pinkaew', prompt: 'The scene is directed in the signature style of Prachya Pinkaew. The action highlights the raw, bone-crunching power of Muay Thai. The choreography is grounded and brutal, with a focus on practical stunts that showcase the incredible athleticism of the performers.' },
    { name: 'Quentin Tarantino (昆汀·塔倫提諾)', prompt: '非線性敘事，風格化的暴力美學，大量流行文化引用和經典配樂，對白充滿張力，如《黑色追緝令》般獨特。' },
    { name: 'Ridley Scott', prompt: 'The scene is directed in the signature style of Ridley Scott. Create a richly detailed, atmospheric world. The action is often brutal and realistic, framed with a painterly eye for composition and texture, whether in historical epics or sci-fi horror.' },
    { name: 'Ringo Lam (林嶺東)', prompt: 'The scene is directed in the signature style of Ringo Lam. Create a gritty, realistic, and often desperate sense of action. The violence is unglamorous and impactful, with characters pushed to their absolute limits in chaotic urban environments.' },
    { name: 'Sam Peckinpah', prompt: 'The scene is directed in the signature style of Sam Peckinpah. The action is a chaotic, slow-motion ballet of violence. The editing is complex and multi-angled, emphasizing the brutal and tragic consequences of every gunshot.' },
    { name: 'Sarah Polley (莎拉·波利)', prompt: '對家庭關係和記憶的細膩探討，充滿同情心的角色塑造，如《她的時代》般深刻而動人。' },
    { name: 'Sergio Leone (賽吉歐·李昂尼)', prompt: '經典義大利西部片，特寫鏡頭和廣闊的沙漠風景形成對比，沉默與暴力並存，如《黃昏三鏢客》。' },
    { name: 'Shane Black', prompt: 'The scene is directed in the signature style of Shane Black. The action is a subversion of genre tropes, often witty, and punctuated by sharp dialogue. The sequences are typically set against a Christmas backdrop and feature buddy-cop dynamics.' },
    { name: 'Stanley Kubrick (史丹利·庫柏力克)', prompt: '冰冷而精確的攝影，對稱構圖，宏大的哲學命題，如《2001太空漫遊》或《發條橘子》。' },
    { name: 'Steven Spielberg (史蒂芬·史匹柏)', prompt: '宏偉的史詩感，探索人性的善惡與希望，運用經典的攝影機運動和音樂，營造《侏羅紀公園》或《E.T.》般的奇幻與冒險。' },
    { name: 'Takashi Miike (三池崇史)', prompt: 'The scene is directed in the signature style of Takashi Miike. The action is surreal, often absurdly violent, and completely unpredictable. The tone can shift from slapstick comedy to horrifying brutality in an instant.' },
    { name: 'Takeshi Kitano (北野武)', prompt: 'The scene is directed in the signature style of Takeshi Kitano. The action is characterized by minimalist long takes, abrupt and shocking moments of violence, and a detached, almost serene aesthetic that contrasts with the brutality.' },
    { name: 'Terrence Malick (泰倫斯·馬力克)', prompt: '詩意的自然光攝影，旁白與意識流敘事，探索人與自然的關係，如《生命之樹》。' },
    { name: 'The Wachowskis (The Matrix)', prompt: 'The scene is directed in the signature style of The Wachowskis. Utilize iconic "bullet time" slow-motion effects, intricate wire-fu martial arts, a cool green and black color grade, and a sense of reality-bending, high-concept action.' },
    { name: 'Timo Tjahjanto', prompt: 'The scene is directed in the signature style of Timo Tjahjanto. The action is relentlessly brutal, gory, and masterfully choreographed. The violence is extreme and visceral, pushing the boundaries of the action genre with a horror-infused intensity.' },
    { name: 'Timur Bekmambetov', prompt: 'The scene is directed in the signature style of Timur Bekmambetov. The action is defined by a wildly inventive use of extreme slow-motion, physics-bending special effects, and a unique visual flair that often feels like a graphic novel brought to life.' },
    { name: 'Tony Scott', prompt: 'The scene is directed in the signature style of Tony Scott. Use a hyper-kinetic style with rapid-fire editing, saturated colors, and a restless camera. The action is slick, high-energy, and has the feel of a high-budget music video.' },
    { name: 'Tsai Ming-liang (蔡明亮)', prompt: '極簡主義的長鏡頭，城市邊緣人物的疏離與孤寂，少對白，注重環境聲和肢體語言，如《愛情萬歲》。' },
    { name: 'Tsui Hark (徐克)', prompt: 'The scene is directed in the signature style of Tsui Hark. Depict fantastical Wuxia-style action with gravity-defying wire-fu, rapid, almost chaotic editing, and imaginative special effects that create a whirlwind of motion and energy.' },
    { name: 'Vittorio De Sica (維托里奧·德西卡)', prompt: '義大利新現實主義，關注二戰後普通人的掙扎，如《偷自行車的人》般感人。' },
    { name: 'Walter Hill', prompt: 'The scene is directed in the signature style of Walter Hill. The action is tough, masculine, and minimalist, with a cool, almost mythic quality. The visuals are gritty and often have a neo-western or comic book-like simplicity.' },
    { name: 'Wes Anderson (韋斯·安德森)', prompt: '極致對稱的構圖，鮮豔飽和的復古色調，古怪的角色和細膩的道具設計，充滿童話感，如《布達佩斯大飯店》。' },
    { name: 'William Friedkin', prompt: 'The scene is directed in the signature style of William Friedkin. Capture a raw, documentary-level of realism. The action, especially car chases, is visceral, dangerous, and feels completely out of control.' },
    { name: 'Wong Kar-wai (王家衛)', prompt: 'The scene is directed in the signature style of Wong Kar-wai. While not a typical action director, capture the moment with a dreamy, atmospheric quality. Use step-printing for blurred motion, neon-drenched, moody lighting, and tight, intimate framing to create a sense of poetic, fleeting intensity.' },
    { name: 'Woody Allen (伍迪·艾倫)', prompt: '知識分子式的幽默對白，對愛情、生活和死亡的哲學思考，城市背景，如《安妮霍爾》。' },
    { name: 'Yasujirō Ozu (小津安二郎)', prompt: '日常生活的溫馨與感傷，固定機位，低機位視角，家庭關係的細膩觀察，如《東京物語》。' },
    { name: 'Yuen Woo-ping (袁和平)', prompt: 'The scene is directed by the legendary martial arts choreographer Yuen Woo-ping. The focus is on intricate, inventive, and masterfully executed hand-to-hand combat and weapon choreography, captured with clear, dynamic camera work that highlights the skill of the fighters.' },
    { name: 'Zack Snyder', prompt: 'The scene is directed in the signature style of Zack Snyder. Employ dramatic speed ramping (alternating between slow-motion and high-speed), high-contrast "crushed blacks" visuals, and carefully composed shots that resemble epic comic book panels.' },
    { name: 'Zhang Yimou (張藝謀)', prompt: '色彩斑斕的視覺美學，史詩般的歷史背景，對抗強權或命運的主題，如《英雄》般詩意的武俠。' }
];

// Example prompts for the initial screen
export const EXAMPLE_PROMPTS = [
    '一隻可愛的貓咪太空人，漂浮在銀河中',
    '一座未來城市的霓虹燈夜景，賽博龐克風格',
    '一幅梵高風格的向日葵星夜畫',
    '一座維多利亞時代的豪宅，住著傳說中的吸血鬼',
    '一位身穿盔甲的女騎士，站在山頂上',
    '一個廢棄的太空站，被外星人佔領',
    '一片超現實的沙漠景觀，瘋狂麥斯車隊正在追逐',
    '一個舒適的書房，窗外下著雨',
];

// For "Inspire Me" feature
export const SUBJECTS = ['一隻貓', '一位機器人', '一位巫師', '一位太空人', '一條龍', '一位偵探'];
export const BACKGROUNDS = ['一座繁華的未來城市', '一片寧靜的魔法森林', '一個廢棄的太空站', '一座維多利亞時代的豪宅', '一片超現實的沙漠景觀'];
export const ACTIONS_POSES = ['正在閱讀一本古老的書', '正在喝咖啡', '正在凝視遠方', '正在跳舞', '正在修理一個複雜的裝置'];
export const EMOTIONS = ['快樂的', '沉思的', '神秘的', '勇敢的', '悲傷的'];
export const CLOTHING = ['現代時尚服裝', '中世紀盔甲', '賽博龐克外套', '優雅的長袍', '蒸汽龐克風格的服飾'];
export const DETAILS_OBJECTS = ['發光的植物', '漂浮的水晶', '古老的時鐘', '未來派的小工具', '一群蝴蝶'];
export const ART_STYLES = ['梵高風格', '達利超現實主義', '日本浮世繪風格', '賽博龐克藝術', '吉卜力工作室動畫風格'];
export const LIGHTING = ['柔和的晨光', '霓虹燈光', '戲劇性的倫勃朗光', '溫暖的燭光', '月光'];
export const COMPOSITIONS = ['對稱構圖', '黃金比例構圖', '特寫鏡頭', '廣角鏡頭', '鳥瞰視角'];
export const TONES_TEXTURES = ['溫暖的色調', '冷酷的藍色調', '高對比度的黑白', '柔和的粉彩色', '粗糙的油畫質感'];

// Function buttons for quick prompt additions
export const FUNCTION_BUTTONS = [
    { label: '公仔手辦', prompt: '4K, create a 1/7 scale commercialized figure of the character, in a realistic style and environment. Place the figure on a computer desk, using a circular transparent acrylic base without any text. On the computer screen, display the ZBrush modeling process of the figure. Next to the computer screen, place a BANDAI-style toy packaging box printed with the original artwork' },
    { label: '三視圖', prompt: 'character design sheet, orthographic view, front view, side view, back view, T-pose, detailed, clean line art, white background' },
    { label: '3D紙雕', prompt: '3D sculpted paper art, layered paper, intricate papercraft, quilling, detailed, delicate lighting' },
    { label: '移除文字', prompt: 'remove all text, subtitles, and logos from the image' },
    { label: '更換背景', prompt: 'change the background to [在此填寫背景], keep the subject' },
    { label: '線稿提取', prompt: 'extract the line art from this image, clean white background' },
    { label: '向量圖標', prompt: 'convert this into a clean, simple, flat 2D vector icon' },
    { label: '黏土模型', prompt: 'claymation style, plasticine model, stop-motion animation look' },
    { label: '像素藝術', prompt: 'pixel art, 16-bit, retro video game style' },
    { label: '雙重曝光', prompt: 'double exposure effect with a silhouette of a person and a forest scene' },
    { label: '低多邊形', prompt: 'low poly art style, geometric, faceted' },
    { label: '黑白素描', prompt: 'black and white pencil sketch, detailed shading' },
    { label: '產品攝影', prompt: 'commercial product photography, clean studio background, professional lighting' },
    { label: '開箱照', prompt: 'Knolling photography, objects arranged neatly at 90-degree angles, flat lay, top-down view, clean studio lighting on a flat surface, organized, hyper-detailed, photorealistic' },
    { label: '等距可愛', prompt: 'Isometric 3D cute art, miniature diorama, soft pastel colors, clay-like texture, clean studio lighting, detailed, high quality' },
    { label: '電影感', prompt: 'cinematic lighting, dramatic, movie still' },
    { label: '吉卜力風格', prompt: 'ghibli studio style, anime, beautiful scenery' },
];

// Art styles for the accordion - Expanded to over 100
export const ART_STYLES_LIST = [
    // --- Modern Art Movements ---
    { en: 'Impressionism', zh: '印象派' },
    { en: 'Post-Impressionism', zh: '後印象派' },
    { en: 'Expressionism', zh: '表現主義' },
    { en: 'Cubism', zh: '立體主義' },
    { en: 'Surrealism', zh: '超現實主義' },
    { en: 'Abs Expressionism', zh: '抽象表現主義' },
    { en: 'Pop Art', zh: '普普藝術' },
    { en: 'Minimalism', zh: '極簡主義' },
    { en: 'Futurism', zh: '未來主義' },
    { en: 'Dadaism', zh: '達達主義' },
    { en: 'Constructivism', zh: '構成主義' },
    { en: 'Fauvism', zh: '野獸派' },
    { en: 'Art Nouveau', zh: '新藝術運動' },
    { en: 'Art Deco', zh: '裝飾藝術' },
    { en: 'Bauhaus', zh: '包浩斯' },
    { en: 'Op Art', zh: '歐普藝術' },
    { en: 'Kinetic Art', zh: '動態藝術' },
    // --- Classical & Historical ---
    { en: 'Renaissance', zh: '文藝復興' },
    { en: 'Baroque', zh: '巴洛克' },
    { en: 'Rococo', zh: '洛可可' },
    { en: 'Neoclassicism', zh: '新古典主義' },
    { en: 'Romanticism', zh: '浪漫主義' },
    { en: 'Realism', zh: '寫實主義' },
    { en: 'Gothic Art', zh: '哥德藝術' },
    { en: 'Byzantine Art', zh: '拜占庭藝術' },
    { en: 'Pre-Raphaelite', zh: '前拉斐爾派' },
    // --- Digital & Contemporary ---
    { en: 'Cyberpunk', zh: '賽博龐克' },
    { en: 'Steampunk', zh: '蒸汽龐克' },
    { en: 'Solarpunk', zh: '太陽龐克' },
    { en: 'Vaporwave', zh: '蒸汽波' },
    { en: 'Glitch Art', zh: '故障藝術' },
    { en: 'Pixel Art', zh: '像素藝術' },
    { en: 'Voxel Art', zh: '體素藝術' },
    { en: 'Low Poly', zh: '低多邊形' },
    { en: 'Fractal Art', zh: '碎形藝術' },
    { en: 'Generative Art', zh: '生成藝術' },
    { en: 'Digital Painting', zh: '數位繪畫' },
    { en: 'Concept Art', zh: '概念藝術' },
    { en: 'Matte Painting', zh: '霧面繪畫' },
    { en: 'Photobashing', zh: '照片拼貼' },
    { en: 'Synthwave', zh: '合成波' },
    { en: 'Holographic', zh: '全息影像' },
    // --- Illustration & Graphic Styles ---
    { en: 'Anime Style', zh: '日本動畫' },
    { en: 'Manga Style', zh: '日本漫畫' },
    { en: 'Ghibli Studio Style', zh: '吉卜力風格' },
    { en: 'Disney Style', zh: '迪士尼風格' },
    { en: 'Cartoon Style', zh: '卡通風格' },
    { en: 'Comic Book Art', zh: '美式漫畫' },
    { en: 'Flat Design', zh: '扁平化設計' },
    { en: 'Vector Art', zh: '向量藝術' },
    { en: 'Infographic Style', zh: '資訊圖表' },
    { en: 'Psychedelic Art', zh: '迷幻藝術' },
    { en: 'Vintage Poster', zh: '復古海報' },
    { en: 'Fantasy Art', zh: '奇幻藝術' },
    { en: 'Sci-Fi Art', zh: '科幻藝術' },
    { en: 'Kids Book Illustration', zh: '童書插畫' },
    // --- Cultural & Regional Styles ---
    { en: 'Ukiyo-e', zh: '浮世繪' },
    { en: 'Ink Wash Painting', zh: '水墨畫' },
    { en: 'Chinese Painting (Guohua)', zh: '國畫' },
    { en: 'Aboriginal Art', zh: '澳洲原住民藝術' },
    { en: 'African Art', zh: '非洲藝術' },
    { en: 'Islamic Art', zh: '伊斯蘭藝術' },
    { en: 'Mandala', zh: '曼陀羅' },
    { en: 'Celtic Knotwork', zh: '凱爾特結' },
    { en: 'Mayan Art', zh: '馬雅藝術' },
    { en: 'Aztec Art', zh: '阿茲特克藝術' },
    { en: 'Indian Mini Painting', zh: '印度細密畫' },
    { en: 'Tibetan Thangka', zh: '西藏唐卡' },
    { en: 'Mexican Muralism', zh: '墨西哥壁畫' },
    // --- Traditional Mediums ---
    { en: 'Oil Painting', zh: '油畫' },
    { en: 'Watercolor Painting', zh: '水彩畫' },
    { en: 'Acrylic Painting', zh: '壓克力畫' },
    { en: 'Gouache Painting', zh: '水粉畫' },
    { en: 'Pencil Sketch', zh: '鉛筆素描' },
    { en: 'Charcoal Drawing', zh: '炭筆素描' },
    { en: 'Ink Drawing', zh: '墨水畫' },
    { en: 'Woodcut Print', zh: '木刻版畫' },
    { en: 'Linocut Print', zh: '油氈版畫' },
    { en: 'Etching', zh: '蝕刻版畫' },
    { en: 'Lithography', zh: '石版畫' },
    { en: 'Collage', zh: '拼貼' },
    { en: 'Mosaic', zh: '馬賽克' },
    { en: 'Stained Glass', zh: '彩繪玻璃' },
    { en: 'Graffiti Art', zh: '塗鴉藝術' },
    { en: 'Street Art', zh: '街頭藝術' },
    { en: 'Calligraphy', zh: '書法' },
    { en: 'Pastel Drawing', zh: '粉彩畫' },
    { en: 'Ballpoint Pen Art', zh: '原子筆藝術' },
    // --- Photographic & Film Styles ---
    { en: 'Cinematic', zh: '電影感' },
    { en: 'Film Noir', zh: '黑色電影' },
    { en: 'Documentary Style', zh: '紀錄片風格' },
    { en: 'Golden Hour Foto', zh: '黃金時刻攝影' },
    { en: 'Blue Hour Foto', zh: '藍色時刻攝影' },
    { en: 'Long Exposure Foto', zh: '長曝光攝影' },
    { en: 'Macro Photography', zh: '微距攝影' },
    { en: 'Double Exposure', zh: '雙重曝光' },
    { en: 'B&W Photography', zh: '黑白攝影' },
    { en: 'Sepia Tone', zh: '棕褐色調' },
    { en: 'Infrared Foto', zh: '紅外線攝影' },
    { en: 'Tilt-Shift Foto', zh: '移軸攝影' },
    { en: 'Lomography', zh: 'LOMO風格' },
    { en: 'Pinhole Photography', zh: '針孔攝影' },
    { en: 'Drone Photography', zh: '空拍攝影' },
    { en: 'Polaroid Photo', zh: '拍立得風格' },
    // --- Unique & Niche ---
    { en: 'Knolling', zh: '擺拍藝術' },
    { en: 'Claymation', zh: '黏土動畫' },
    { en: 'Quilling', zh: '衍紙' },
    { en: 'Origami', zh: '摺紙' },
    { en: 'Tattoo Art', zh: '紋身藝術' },
    { en: 'Body Painting', zh: '人體彩繪' },
    { en: 'Light Painting', zh: '光繪' },
    { en: 'Diorama', zh: '立體透視模型' },
    { en: 'Miniature Faking', zh: '微縮景觀' },
    { en: 'Anamorphic Art', zh: '變形藝術' },
    { en: 'Cross-Stitch', zh: '十字繡' },
    { en: 'Stipple Art', zh: '點畫' },
    { en: 'Knolling Foto', zh: '開箱照' },
];

export const EDITING_EXAMPLES = [
    {
      category: '主體變換',
      examples: [
        { title: '變換材質', prompt: '將 [主體] 的材質變成 [玻璃/木頭/金屬/石頭]' },
        { title: '添加發光效果', prompt: '讓 [主體] 的 [特定部位] 發出 [顏色] 的光芒' },
        { title: '風格化', prompt: '將 [主體] 變成 [像素/卡通/素描] 風格' },
        { title: '擬人化', prompt: '將 [物體] 擬人化，賦予其人類的表情和動作' },
      ]
    },
    {
      category: '背景與環境',
      examples: [
        { title: '更換背景', prompt: '將背景更換為 [未來城市/魔法森林/廢棄工廠]' },
        { title: '改變天氣', prompt: '將天氣變為 [下雨/下雪/起霧/黃昏]' },
        { title: '添加元素', prompt: '在背景中添加 [漂浮的島嶼/巨大的月亮/飛過的龍]' },
        { title: '時間變換', prompt: '將場景的時間變為 [白天/夜晚/黎明]' },
      ]
    },
    {
      category: '構圖與視角',
      examples: [
        { title: '改變視角', prompt: '將視角變為 [鳥瞰/仰視/魚眼]' },
        { title: '聚焦主體', prompt: '使用淺景深效果，模糊背景，突出主體' },
        { title: '延伸畫布 (Outpainting)', prompt: '將畫布向 [上下左右] 延伸，並智慧填充內容' },
        { title: '畫面裁切', prompt: '將畫面裁切為 [16:9/4:3/方形] 比例，重新構圖' },
      ]
    },
    {
      category: '特效與氛圍',
      examples: [
        { title: '添加動態模糊', prompt: '為主體添加運動模糊效果，營造速度感' },
        { title: '電影感色調', prompt: '為整張圖片套上電影感色調，參考 [駭客任務/銀翼殺手] 的風格' },
        { title: '雙重曝光', prompt: '將 [主體輪廓] 與 [另一張圖片，如森林/星空] 進行雙重曝光' },
        { title: '故障藝術', prompt: '為圖片添加 Glitch Art (故障藝術) 效果，如數據錯誤、色彩分離' },
      ]
    },
];
